version: "3.3"
services:
  db:
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: 17042002
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: api_rest
      MYSQL_PASSWORD: 17042002
    ports:
      - "3307:3306"
    command: >
      --init-connect='GRANT ALL PRIVILEGES ON *.* TO "root"@"%" WITH GRANT OPTION; FLUSH PRIVILEGES;'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ../Backend/
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../Frontend/  # Directorio donde se encuentra el Dockerfile
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "4200:4200"

