name: Selenium Tests

on:
  push:
    branches:
      - main
      - tester
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    env:
      # Esta variable se usa en BaseTest para conectarse al Selenium remoto.
      SELENIUM_REMOTE_URL: http://localhost:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Wait for Selenium to be ready
        run: |
          echo "Waiting for Selenium to be ready..."
          retries=24
          until curl -s http://localhost:4444/status | grep -q -E '"ready":\s*true'; do
            if [ $retries -le 0 ]; then
              echo "Selenium not ready after multiple attempts, failing..."
              curl -s http://localhost:4444/status
              exit 1
            fi
            echo "Selenium not ready, waiting..."
            retries=$((retries-1))
            sleep 5
          done
          echo "Selenium is ready!"

      - name: Run Selenium Tests with Maven Debug
        run: mvn test -Dtest="com.tfg.futstats.selenium.**" -e -X
        working-directory: ./Backend

      - name: Upload Surefire Reports on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: ./Backend/target/surefire-reports
