name: CD - Deploy to Azure
 
 
on:
  push:
    branches:
      - main
 
permissions:
  id-token: write
  contents: read
 
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
  
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
 
    - name: Build images
      run: docker build -t danielpandolfo/futstats:latest -f Dockerfile .
 
    - name: Push images
      run: docker push danielpandolfo/futstats:latest
        
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
      - name: Start MySQL database
        run: |
          az mysql flexible-server start \
            --name futstats \
            --resource-group ${{ secrets.AZURE_GROUP }}
 
      - name: Deploy to Azure
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_GROUP }} \
            --name futstats \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/futstats:${{ needs.publish.outputs.tag }} \
            --dns-name-label futstats-app \
            --registry-login-server index.docker.io \
            --registry-username ${{ secrets.DOCKERHUB_USERNAME }} \
            --registry-password ${{ secrets.DOCKERHUB_TOKEN }} \
            --ports 8443 \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5 \
            --environment-variables \
              SPRING_DATASOURCE_URL="jdbc:mysql://futstats.mysql.database.azure.com:3306/apirest?useSSL=true" \
              SPRING_DATASOURCE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
              SPRING_DATASOURCE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
              RUNNING_IN_DOCKER="true" \
              SERVER_PORT=8443
