name: CD - Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/futstats
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,format=short
          type=ref,event=branch
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/futstats:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/futstats:buildcache,mode=max

    - name: Verify image was pushed
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/futstats:latest
        docker images | grep ${{ secrets.DOCKERHUB_USERNAME }}/futstats

  deploy:
    environment: production
    permissions:
      id-token: write
    needs: publish
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Start MySQL database
        run: |
          az mysql flexible-server start \
            --name futstats \
            --resource-group ${{ secrets.AZURE_GROUP }}

      - name: Deploy to Azure
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_GROUP }} \
            --name futstats \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/futstats:${{ needs.publish.outputs.tag }} \
            --dns-name-label futstats-app \
            --registry-login-server index.docker.io \
            --registry-username ${{ secrets.DOCKERHUB_USERNAME }} \
            --registry-password ${{ secrets.DOCKERHUB_AZURE_TOKEN }} \
            --ports 8443 \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5 \
            --environment-variables \
              SPRING_DATASOURCE_URL="jdbc:mysql://futstats.mysql.database.azure.com:3306/apirest?useSSL=true" \
              SPRING_DATASOURCE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
              SPRING_DATASOURCE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
              RUNNING_IN_DOCKER="true" \
              SERVER_PORT=8443

      - name: Verify deployment
        run: |
          az container show \
            --resource-group ${{ secrets.AZURE_GROUP }} \
            --name futstats \
            --query properties.instanceView.state
